# Generated by Django 5.1.4 on 2025-01-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_register',
        ),
    ]
