# Generated by Django 5.1.4 on 2025-01-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=50)),
                ('answers', models.CharField(max_length=50)),
            ],
        ),
    ]
