# Generated by Django 5.1.4 on 2025-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
            ],
        ),
    ]
