# Generated by Django 5.1.4 on 2025-03-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fert_name', models.CharField(max_length=50)),
                ('fert_details', models.CharField(max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_crop')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest', models.CharField(max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_crop')),
            ],
        ),
    ]
