# Generated by Django 5.1.4 on 2025-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_district', models.CharField(max_length=30)),
                ('user_place', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assests/User/Photo')),
                ('user_gender', models.CharField(max_length=30)),
                ('user_dob', models.CharField(max_length=30)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_confirm', models.CharField(max_length=30)),
            ],
        ),
    ]
