# Generated by Django 5.1.4 on 2025-02-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertil_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pestdetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=30)),
                ('soiltype', models.CharField(max_length=30)),
                ('soildepth', models.CharField(max_length=30)),
                ('rainfall', models.CharField(max_length=30)),
            ],
        ),
    ]
