# Generated by Django 5.1.4 on 2025-02-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_fertilizer',
        ),
        migrations.DeleteModel(
            name='tbl_pestdetect',
        ),
        migrations.DeleteModel(
            name='tbl_Predict',
        ),
    ]
