# Generated by Django 5.1.4 on 2025-02-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_initial'),
        ('User', '0002_delete_tbl_fertilizer_delete_tbl_pestdetect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertil_name', models.CharField(max_length=30)),
                ('fert_result', models.CharField(max_length=30)),
                ('fert_date', models.DateField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pestdetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=30)),
                ('pest_result', models.CharField(max_length=30)),
                ('pest_date', models.DateField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=30)),
                ('soiltype', models.CharField(max_length=30)),
                ('soildepth', models.CharField(max_length=30)),
                ('rainfall', models.CharField(max_length=30)),
                ('predict_result', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
