# Generated by Django 5.1.4 on 2025-02-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_initial'),
        ('Owner', '0011_tbl_plot_tbl_gallery'),
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_content', models.CharField(max_length=30)),
                ('req_status', models.IntegerField(default=0)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
