# Generated by Django 5.1.4 on 2025-03-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_addrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_fertilizer',
        ),
    ]
