# Generated by Django 5.1.4 on 2025-03-09 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_owner'),
        ('User', '0005_delete_tbl_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fertilizerdetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertil_name', models.CharField(max_length=30)),
                ('fert_result', models.CharField(max_length=30)),
                ('fert_date', models.DateField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
