# Generated by Django 5.1.4 on 2025-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_email', models.CharField(max_length=30)),
                ('owner_pass', models.CharField(max_length=30)),
                ('owner_address', models.CharField(max_length=30)),
                ('owner_proof', models.FileField(upload_to='Assests/Owner/')),
            ],
        ),
    ]
