# Generated by Django 5.1.4 on 2025-01-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_pass', models.CharField(max_length=50)),
                ('new_pass', models.CharField(max_length=50)),
                ('con_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
