# Generated by Django 5.1.4 on 2025-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_tbl_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
