# Generated by Django 5.1.4 on 2025-01-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_tbl_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_editprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_name', models.CharField(max_length=50)),
                ('ed_email', models.CharField(max_length=50)),
                ('ed_addr', models.CharField(max_length=50)),
            ],
        ),
    ]
