# Generated by Django 5.1.4 on 2025-02-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_type'),
        ('Owner', '0004_tbl_condition_tbl_editprof'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmetrics', models.CharField(max_length=30)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
