# Generated by Django 5.1.4 on 2025-02-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_tbl_plot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_plot',
        ),
    ]
