# Generated by Django 5.1.4 on 2025-02-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_delete_tbl_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmetrics', models.CharField(max_length=30)),
            ],
        ),
    ]
