# Generated by Django 5.1.4 on 2025-02-06 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0007_tbl_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_myprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='Assests/Owner/')),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_plot')),
            ],
        ),
    ]
