# Generated by Django 5.1.4 on 2025-02-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_tbl_myprofile_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_change',
        ),
        migrations.DeleteModel(
            name='tbl_editprof',
        ),
    ]
