# Generated by Django 5.1.4 on 2025-02-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0009_delete_tbl_change_delete_tbl_editprof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='plot_id',
        ),
        migrations.DeleteModel(
            name='tbl_myprofile',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_plot',
        ),
    ]
