# Generated by Django 5.1.4 on 2025-02-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_type'),
        ('Owner', '0010_remove_tbl_gallery_plot_id_delete_tbl_myprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmetrics', models.CharField(max_length=30)),
                ('plot_status', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_owner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='Assests/Owner/')),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_plot')),
            ],
        ),
    ]
