# Generated by Django 5.1.4 on 2025-02-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_type'),
        ('Owner', '0011_tbl_plot_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plottype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_plot')),
            ],
        ),
    ]
