# Generated by Django 5.1.4 on 2025-02-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0012_tbl_plottype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_condition',
        ),
    ]
