# Generated by Django 5.1.4 on 2025-02-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0013_delete_tbl_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_plot')),
            ],
        ),
    ]
