# Generated by Django 5.1.4 on 2025-02-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0014_tbl_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complain',
        ),
    ]
