# Generated by Django 5.1.4 on 2025-02-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_owner'),
        ('Owner', '0016_tbl_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_plot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_owner'),
        ),
        migrations.AlterField(
            model_name='tbl_complain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_owner'),
        ),
        migrations.DeleteModel(
            name='tbl_owner',
        ),
    ]
