# Generated by Django 5.1.4 on 2025-02-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0017_alter_tbl_plot_owner_alter_tbl_complain_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complain',
        ),
    ]
